config/routes.rb
Rails.application.routes.draw do
  get 'weather/forecast'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  # Action to fetch the weather forecast for a given zip code
  def forecast
    @zip_code = params[:address]
    return unless @zip_code.present?

    @forecast_data, @from_cache = WeatherService.new(@zip_code).fetch_forecast

    respond_to do |format|
      format.html
      format.turbo_stream { render partial: "weather/weather_data" }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecastApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_weather_data.html.erb
<div>
  <h2>Weather Forecast for <%= @zip_code %></h2>
  <p><strong>Temperature:</strong> <%= weather_data[:temperature] %>°C</p>
  <p><strong>High:</strong> <%= weather_data[:high] %>°C</p>
  <p><strong>Low:</strong> <%= weather_data[:low] %>°C</p>
  <p><strong>Description:</strong> <%= weather_data[:description] %></p>
</div>

app/views/weather/forecast.html.erb
<h1>Check Weather</h1>

<%= form_with url: weather_forecast_path, method: :get, data: { turbo_frame: "weather_frame" }, local: true do |form| %>
  <div>
    <%= form.label :address, "Enter Zip Code:" %>
    <%= form.text_field :address, placeholder: "e.g., 600001", required: true %>
  </div>
  <br>
  <div>
    <%= form.submit "Get Forecast" %>
    <%= button_tag "Clear", type: "reset", class: "clear-button" %>
  </div>
<% end %>


<turbo-frame id="weather_frame">
  <% if @forecast_data %>
    <%= render partial: "weather/weather_data", locals: { weather_data: @forecast_data } %>
  <% end %>
</turbo-frame>